name: CI Workflow C Make

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Install cmocka
      run: |
        sudo apt-get update
        sudo apt-get install libcmocka-dev
      # https://ubuntu.pkgs.org/20.10/ubuntu-universe-amd64/libcmocka-dev_1.1.5-2_amd64.deb.html

    - name: Build with make
      run: make build
    - name: Test with make
      run: |
        make test
        make clean

    - name: Test the example
      run: |
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:./include
        export LIBRARY_PATH=$LIBRARY_PATH:./lib
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:./lib
        make example
        make clean

    - name: Keep binary files
      uses: actions/upload-artifact@v2
      with:
        name: Binaries_Linux_x64
        path: |
          ./include/*.h
          ./lib/*.so
          ./src
          ./LICENSE
          ./README.md
